name: Generate Goosepaper and upload

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Goosepaper
        uses: addnab/docker-run-action@v3
        with:
          image: j6k4m8/goosepaper:latest
          options: -v ${{ github.workspace }}:/goosepaper/mount
          run: goosepaper -c mount/config.json -o mount/generated.pdf
      - name: Upload generated pdf artifact
        uses: actions/upload-artifact@v3
        with:
          name: goosepaper
          path: ./generated.pdf
          retention-days: 7
  upload:
    runs-on: ubuntu-latest
    needs: generate
    env:
      UPLOAD_DIRECTORY: Daily
    steps:
      - name: Set up rmapi
        run: |
          wget https://github.com/juruen/rmapi/releases/download/v0.0.25/rmapi-linuxx86-64.tar.gz
          tar -xvzf rmapi-linuxx86-64.tar.gz
      - name: Determine today's date
        id: date-determinator
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name: Download generated pdf artifact
        uses: actions/download-artifact@v3
        with:
          name: goosepaper
          path: ./${{ steps.date-determinator.outputs.CURRENT_DATE }}.pdf
      - name: Prepare rmapi.conf
        shell: bash
        env:
          RMAPI_CONFIG_FILE_BASE64: ${{ secrets.RMAPI_CONFIG_FILE_BASE64 }}
        run: |
          echo "$RMAPI_CONFIG_FILE_BASE64" | base64 -d > rmapi.conf
      - shell: bash
        env:
          RMAPI_CONFIG: ./rmapi.conf
        run: |
          ./rmapi mkdir $UPLOAD_DIRECTORY
          ./rmapi put ./${{ steps.date-determinator.outputs.CURRENT_DATE }}.pdf $UPLOAD_DIRECTORY
