name: Generate Goosepaper and upload

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Goosepaper
        uses: addnab/docker-run-action@v3
        with:
          image: j6k4m8/goosepaper:latest
          options: -v ${{ github.workspace }}:/goosepaper/mount
          run: goosepaper -c mount/config.json -o mount/generated.pdf
      - uses: actions/upload-artifact@v3
        with:
          name: goosepaper
          path: ./generated.pdf
  upload:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Set up rmapi
        run: |
          curl https://github.com/juruen/rmapi/releases/download/v0.0.25/rmapi-linuxx86-64.tar.gz --output rmapi.tar.gz
          tar -xf rmapi.tar.gz
      - run: |
          ls -la
